# Generated by Django 3.1.7 on 2021-03-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='victims_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('plot_no', models.CharField(max_length=25)),
                ('project_name', models.CharField(max_length=150)),
                ('paid_amount', models.FloatField()),
                ('cnic', models.CharField(max_length=50)),
                ('whatsapp_group', models.CharField(max_length=150)),
                ('receipt_no', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=25)),
                ('additiona_details', models.TextField()),
                ('created_on', models.DateField()),
            ],
        ),
    ]
