# Generated by Django 3.1.7 on 2021-03-07 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edenVictims', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='victims_data',
            old_name='additiona_details',
            new_name='additional_details',
        ),
    ]
