# Generated by Django 3.1.7 on 2021-03-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edenVictims', '0002_auto_20210307_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victims_data',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
