# Generated by Django 3.1.7 on 2021-03-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edenVictims', '0003_auto_20210307_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='victims_data',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='victims_data',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
