# Generated by Django 3.1.7 on 2021-03-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edenVictims', '0005_auto_20210307_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victims_data',
            name='city',
            field=models.CharField(default='Lahore', max_length=50),
        ),
        migrations.AlterField(
            model_name='victims_data',
            name='country',
            field=models.CharField(default='Pakistan', max_length=50),
        ),
    ]
