# Generated by Django 3.1.7 on 2021-03-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edenVictims', '0007_auto_20210308_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victims_data',
            name='additional_details',
            field=models.TextField(null=True),
        ),
    ]
