# Generated by Django 3.1.7 on 2021-03-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edenVictims', '0008_auto_20210308_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victims_data',
            name='additional_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='victims_data',
            name='city',
            field=models.CharField(default='Lahore', max_length=50),
        ),
        migrations.AlterField(
            model_name='victims_data',
            name='country',
            field=models.CharField(default='Pakistan', max_length=50),
        ),
        migrations.AlterField(
            model_name='victims_data',
            name='whatsapp_group',
            field=models.CharField(default='Eden Victims Group', max_length=150),
        ),
    ]
