# Generated by Django 3.1.7 on 2021-03-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edenVictims', '0009_auto_20210308_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victims_data',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
